### ISSUE TITLE
Fitting 'total water' profile

### ISSUE THREAD

**Issue by barthac** [EFerriss/Pynams#10]
I have split my profiles into different peaks. When I want the total water, I add the areas from the different peaks. However, I can't fit this total water with your fitD function since it is not technically a 'profile'. 
Is there a way to turn my list of total water contents into a profile so that I can fit it?

**Comment by EFerriss** [comment]
Try 
profile.areas = your summed area list
profile.plot_area_list()

**Comment by EFerriss** [comment]
Actually, no, that won't work because it's going to re-make the areas every time. Let me fiddle with it.

**Comment by EFerriss** [comment]
pynams updated - you should be able to set the profile.areas directly and then it'll use those in the plotting command.

**Comment by barthac** [comment]
Great, thanks!

**Comment by EFerriss** [comment]
Let me know if it works, and if it does, you can close the issue.

**Comment by EFerriss** [comment]
Oh, it's not profile.plot_areas_list(), it's the usual plot command

**Comment by barthac** [comment]
It worked! Thanks!

**Comment by EFerriss** [comment]
It just occurred to me to add a caution: Because profile.plot_area_profile no longer automatically updates the profile.areas based on the current baselines, if you plot an area profile, change baselines, and then want to plot the new areas for the new baselines, you must first update the profile.areas by running profile.make_area_list()

**Comment by EFerriss** [comment]
I updated profile.get_baselines() to automatically run profile.make_area_list() so this problem doesn't come up and the areas are automatically updated.
